config/routes.rb
Blogit::Engine.routes.draw do

  # Keep these above the posts resources block
  get "posts/page/:page" => "posts#index"
  get "posts/tagged/:tag" => 'posts#tagged', as: :tagged_blog_posts

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "/" => "posts#index", as: :blog_root
end

app/models/blogit/comment.rb
module Blogit
  class Comment < ActiveRecord::Base

    # require custom validators
    require "validators"
    include Validators

    # ================
    # = Associations =
    # ================

    belongs_to :post, class_name: "Blogit::Post",
      foreign_key: "post_id", counter_cache: true, touch: true

    # TODO: Check if this is optimal
    URL_REGEX   = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\Z/ix

    # TODO: Check if this is optimal
    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i

    # =============
    # = Callbacks =
    # =============

    before_validation :format_website

    # ==============
    # = Attributes =
    # ==============

    # nickname acts as a "honeypot" to catch spam
    # the form field should be hidden using CSS and so
    # if present, must be spam.
    #
    # @attribute
    attr_accessor :nickname


    # ===============
    # = Validations =
    # ===============

    # nickname acts as a "honeypot" to catch spam
    # the form field should be hidden using CSS and so
    # if present, must be spam.
    validates :nickname, absence: true
    validates :name, presence: true
    validates :email, presence: true, format: {with: EMAIL_REGEX, allow_blank: true }
    validates :body, presence: true, length: { minimum: 4, allow_blank: true}
    validates :website, format: {with: URL_REGEX, allow_blank: true}

  private

    # Prepend http to the url before the validation check
    def format_website
      if self.website.present? and self.website !~ /^http/i
        self.website = "http://#{self.website}"
      end
    end

  end
end

app/models/blogit/post.rb
module Blogit
  class Post < ActiveRecord::Base
    
    require "kaminari"
    require "acts-as-taggable-on"

    acts_as_taggable

    self.paginates_per(Blogit.configuration.posts_per_page)

    # ===============
    # = Validations =
    # ===============

    validates :title, presence: true, length: { minimum: 10, maximum: 66 }

    validates :body,  presence: true, length: { minimum: 10 }
    
    validates :description, presence: Blogit.configuration.show_post_description

    validates :blogger_id, presence: true

    validates :state, presence: true

    # ================
    # = Associations =
    # ================

    ##
    # The blogger (User, Admin, etc.) who wrote this Post
    #
    # Returns a Blogger (polymorphic type)
    belongs_to :blogger, :polymorphic => true

    ##
    # The {Comment Comments} written on this Post
    #
    # Returns an ActiveRecord::Relation instance
    has_many :comments, :class_name => "Blogit::Comment"

    # ==========
    # = Scopes =
    # ==========

    scope :for_index, lambda { |page_no = 1| 
      active.order("created_at DESC").page(page_no) }
      
    scope :active, lambda { where(state:  Blogit.configuration.active_states ) }


    # The posts to be displayed for RSS and XML feeds/sitemaps
    #
    # Returns an ActiveRecord::Relation
    def self.for_feed
      active.order('created_at DESC')
    end
    
    # Finds an active post with given id
    #
    # id - The id of the Post to find
    #
    # Returns a Blogit::Post
    # Raises ActiveRecord::NoMethodError if no Blogit::Post could be found
    def self.active_with_id(id)
      active.find(id)
    end
    
    # ====================
    # = Instance Methods =
    # ====================

    # TODO: Get published at working properly!
    def published_at
      created_at
    end
    
    def to_param
      "#{id}-#{title.parameterize}"
    end
    
    # The content of the Post to be shown in the RSS feed.
    #
    # Returns description when Blogit.configuration.show_post_description is true
    # Returns body when Blogit.configuration.show_post_description is false
    def short_body
      if Blogit.configuration.show_post_description
        description
      else
        body
      end
    end
    
    def comments
      check_comments_config
      super()
    end
    
    def comments=(value)
      check_comments_config
      super(value)
    end
    

    # The blogger who wrote this {Post Post's} display name
    #
    # Returns the blogger's display name as a String if it's set.
    # Returns an empty String if blogger is not present.
    # Raises a ConfigurationError if the method called is not defined on {#blogger}
    def blogger_display_name
      return "" if blogger.blank?
      if blogger.respond_to?(Blogit.configuration.blogger_display_name_method)
        blogger.send(Blogit.configuration.blogger_display_name_method)
      else
        method_name = Blogit.configuration.blogger_display_name_method
        raise ConfigurationError, "#{blogger.class}##{method_name} is not defined"
      end
    end

    # If there's a blogger and that blogger responds to :twitter_username, returns that.
    # Otherwise, returns nil
    def blogger_twitter_username
      if blogger and blogger.respond_to?(:twitter_username)
        blogger.twitter_username
      end
    end
    

    private


    def check_comments_config
      unless Blogit.configuration.include_comments == :active_record
        raise RuntimeError, 
          "Posts only allow active record comments (check blogit configuration)"
      end
    end
    
  end
end

app/controllers/blogit/application_controller.rb
module Blogit

  # Inherits from the application's controller instead of ActionController::Base
  class ApplicationController < ::ApplicationController

    helper Blogit::ApplicationHelper
    helper Blogit::LayoutHelper
    helper Blogit::PostsHelper
    helper Blogit::CommentsHelper
    
    helper_method :blogit_conf

    # A helper method to access the {Blogit::configuration} at the class level.
    #
    # Returns a Blogit::Configuration
    def self.blogit_conf
      Blogit::configuration
    end

    # A helper method to access the {Blogit::configuration} at the controller instance
    #   level.
    #
    # Returns a Blogit::Configuration
    def blogit_conf
      self.class.blogit_conf
    end

  end
  
end

app/controllers/blogit/comments_controller.rb
module Blogit
  
  # Handles requests for creating Blogit::Comments 
  class CommentsController < ApplicationController

    # Accessor method for the comment being created
    #
    # Returns a Blogit::Comment
    attr_reader :comment
    
    # Accessor method for the Post we're adding a Comment to
    #
    # Returns Post
    attr_reader :post
    
    # Handles POST requests to /blogit/comments.html and /blogit/comments.js
    #
    # Yields #comment if called with a block (useful for calling super from subclasses)
    def create
      set_post_from_post_id
      set_comment_as_new
      comment.save
      yield comment if block_given?
      respond_to do |format|
        format.js   { create_respond_to_js }
        format.html { create_respond_to_html }
      end
    end


    private


    # Set this controller's post attribute to the current Post
    def set_post_from_post_id
      @post = Blogit::Post.active_with_id(params[:post_id])
    end

    # Set this controller's comment attribute as a new comment with params
    def set_comment_as_new
      @comment = post.comments.new(comment_params)
    end

    # The create action render call when format is JS
    def create_respond_to_js
      render status: (comment.persisted? ? :created : :bad_request)
    end

    # The create action render call when format is HTML    
    def create_respond_to_html
      if comment.persisted?
        redirect_to(post, 
          notice: t(:successfully_added_comment, scope: 'blogit.comments'))
      else
        render "blogit/posts/show"
      end  
    end
    
    # The comment attribute params 
    # 
    # Returns a Hash
    def comment_params
      params.require(:comment).permit(:name, :nickname, :email, :body, :website)
    end
    
  end
  
end

app/controllers/blogit/posts_controller.rb
module Blogit

  # Handles requests for viewing Blogit::Posts
  class PostsController < ::Blogit::ApplicationController

    # The current Blogit::Post being displayed.
    #
    # Returns a Blogit::Post with id from params
    attr_reader :post

    # The current Posts being displayed
    #
    # Returns ActiveRecord::Relation for Post table
    attr_reader :posts
    
    # If a layout is specified, use that. Otherwise, fall back to the default
    layout Blogit.configuration.layout if Blogit.configuration.layout

    # Handles GET requests to /blogit/posts.html, /blogit/posts.xml, and /blogit/posts.rss
    # Possible formats include:
    #
    # "XML" -  calls {#set_posts_for_feed}.
    # "RSS" -  calls {#set_posts_for_feed}.
    # "HTML" - calls {#set_posts_for_index_page}.
    #
    # Yields #posts if called with a block (useful for calling super from subclasses)
    #
    # Returns nil
    def index
      respond_to do |format|
        format.xml  { set_posts_for_feed }
        format.rss  { set_posts_for_feed }
        format.html { set_posts_for_index_page }
      end
      yield(posts) if block_given?      
    end

    # Handles GET requests to /blogit/posts/:id.html
    #
    # Yields #post if called with a block (useful for calling super from subclasses)
    def show
      set_post
      yield post if block_given?
    end

    # Handles GET requests to /blogit/posts/tagged/:tag.html. Renders the index template
    # with Posts tagged with tag in *tag* parameter
    #
    # Yields #posts if called with a block (useful for calling super from subclasses)
    def tagged
      set_posts_for_tagged_page
      yield(posts) if block_given?      
      render :index
    end


    private
    
    
    # Set {#post} based on the :id param
    def set_post
      @post = Post.active_with_id(params[:id])
    end
    
    # The page parameter value for the current locale
    def page_number
      @page_number ||= params[Kaminari.config.param_name]
    end
    
    # Sets {#posts} for the XML feed
    def set_posts_for_feed
      @posts ||= Post.for_feed
    end

    # Sets {#posts} for the HTML index page
    # 
    # tag - The tag name to filter Posts by (default: nil)
    #
    def set_posts_for_index_page(tag = nil)
      @posts ||= Post.for_index(page_number)
    end
    
    # Sets {#posts} for the HTML index page when a tag parameter is present
    # 
    def set_posts_for_tagged_page
      @posts = set_posts_for_index_page.tagged_with(params[:tag])
    end

  end

end

app/helpers/blogit/application_helper.rb
module Blogit
  module ApplicationHelper
    
    # Format content using the {Blogit::Configuration#default_parser_class default_parser_class}
    #
    # content - A String containing the content to be formatted (defaults: nil)
    # block   - A Proc that returns a String of content to be formatted
    #
    # Examples
    # 
    #   format_content("# This is a Markdown header")
    #   # => "<h1>This is a Markdown header</h1>"
    #
    #   format_content do 
    #     "some text"
    #   end
    #   # => "<p>some text</p>"
    #
    # Returns an HTML safe String.
    def format_content(content = nil, &block)
      content = capture(&block) if block_given?
      parser  = Blogit::configuration.default_parser_class.new(content)
      parser.parsed.to_s.html_safe
    end

    # The first error message for an ActiveRecord::Base model instance attribute
    #
    # object    - An ActiveRecord::Base instance to check
    # attribute - A Symbol or String with the attribute name to check errors on
    #
    # Examples
    #
    #  errors_on(@user, :first_name)
    #  # => "Can't be blank"
    #
    # Returns a String with the error message
    def errors_on(object, attribute)
      error_message = object.errors[attribute].first
      content_tag(:span, error_message, class: "blogit_error_message") if error_message
    end

    # A helper method for creating a div tag with class 'field'. Used for separating
    # form fields.
    #
    # content_or_options - The content to include in the div when not using a block. The
    #                      options Hash when using a block
    # options            - The options when not using a block
    # block              - A block that returns HTML content to include in the div
    #
    # Returns an HTML safe String
    def field(content_or_options = {}, options ={}, &block)
      div_tag_with_default_class("field", content_or_options, options, &block)
    end

    # A helper method for creating a div tag with class 'actions'. Used as a wrapper
    # for form actions.
    #
    # content_or_options - The content to include in the div when not using a block. The
    #                      options Hash when using a block
    # options            - The options when not using a block
    # block              - A block that returns HTML content to include in the div
    #
    # Returns an HTML safe String
    def actions(content_or_options={}, options ={}, &block)
      div_tag_with_default_class("actions", content_or_options, options, &block)
    end
    
    
    private
    
    
    # Creates an HTML div with a default class value added
    #
    # default_class      - The CSS class name to add to the div
    # content_or_options - The content to include in the div when not using a block. The
    #                      options Hash when using a block
    # options            - The options when not using a block
    # block              - A block that returns HTML content to include in the div
    #
    #
    # Returns an HTML safe String
    def div_tag_with_default_class(default_class, content_or_options, options, &block)
      if block_given?
        options = content_or_options
        content = capture(&block)
      else
        content = content_or_options
      end
      options[:class] = Array(options[:class]) + [default_class]
      content_tag(:div, content, options)
    end

  end
  
end

app/helpers/blogit/comments_helper.rb
module Blogit
  
  module CommentsHelper
    
    # The commenter's name for a Comment. When the Comment has a website, includes an html
    # link containing their name. Otherwise, just shows the name as a String.
    #
    # comment - A {Blogit::Comment}
    #
    # Returns a String containing the commenter's name.
    def name_for_comment(comment)
      if comment.website?
        link_to(comment.name, comment.website, class: "blogit_comment__name_link")
      else
        comment.name
      end + " " + t('wrote', scope: "blogit.comments")
    end
    
  end
end

app/helpers/blogit/layout_helper.rb
module Blogit
  
  module LayoutHelper

    # Sets or returns the title for a page
    #
    # content - The content to include in the HTML title tag.
    #
    # Returns a String
    def title(content=nil)
      if content
        content_for(:title, content)
      else
        content_for(:title)
      end
    end
    
    # Sets or returns the description for a page. Formats the content if it's Markdown or
    # HTML and strips out the HTML tags.
    #
    # content - The content to include in the HTML meta description tag.
    #
    # Returns a String    
    def description(content=nil)
      if content
        content_for(:description, strip_tags(format_content(content)).html_safe)
      else
        content_for(:description)
      end
    end
    
  end
end

app/helpers/blogit/posts_helper.rb
module Blogit
  module PostsHelper
    
    require "blogit/archive"
    
    # Renders the comments for a {Post} based on the
    # {Blogit::Configuration::include_comments} configuration
    def comments_for_post(post)
      comment_type = Blogit.configuration.include_comments
      render(partial: "blogit/comments/#{comment_type}_comments", 
        locals: { post: post, comment: Blogit::Comment.new })
    end

    # Renders the comments for a JS share bar based on the
    # {Blogit::Configuration::include_share_bar} configuration
    def share_bar_for_post(post)
      return "" unless Blogit.configuration.include_share_bar
      render(partial: "blogit/posts/share_bar", locals: { post: post})
    end
    
    # Returns the {Post Posts} that share one or more of the same tags for a given post
    #
    # post - A {Post} instance
    #
    # Returns a collection of {Post Posts}
    def related_posts_for_post(post)
      post.find_related_on_tags.active
    end

    # Creates a ul tag tree with posts by year and months. Include blogit/archive.js in
    # your js to enabled expand collapse.
    #
    # Examples
    #
    #   <%= archive_list_for_posts(@posts) %>
    #   # => <div class="blogit_archive">
    #          <ul class="blogit_archive__list blogit_archive__list--years">
    #            ...
    #          </ul>
    #        </div>
    # 
    # Returns an HTML safe String
    def archive_list_for_posts(archive_posts)
      render Blogit::Archive::List.new(archive_posts)
    end

  end

end

app/views/blogit/posts/_archiveable.html.erb
<li class="blogit_archive__item blogit_archive__item--post">
  <%= link_to(post.title, post_path(post), class: "blogit_archive__item_link") %>
</li>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blogit_post_spacer">

app/views/blogit/posts/_blogger_information.html.erb
<div class="blogit_post__information">
  <span class="blogit_post__blogger">
    <%= t(:written_by, scope: 'blogit.posts', 
      author: post.blogger_display_name) %>
  </span>

  <%= time_tag(post.created_at, pubdate: true, 
    class: "blogit_post__published_at" ,format: blogit_conf.datetime_format) %>
</div>

app/views/blogit/posts/_meta_tags.html.erb
<%= tag(:meta, name: "description", content: description) %>
<%= tag(:meta, property: "author", content: post.blogger_display_name) %>

<!-- Open Graph Tags: http://ogp.me -->
<%= tag(:meta, property: "og:site_name", content: "") %>
<%= tag(:meta, property: "og:url", content: url_for(params)) %>
<%= tag(:meta, property: "og:title", content: title) %>
<%= tag(:meta, property: "og:description", content: description) %>
<%= tag(:meta, property: "og:type", content: "article") %>
<% # TODO: Support images in blogit (sorry) %> 
<%= tag(:meta, property: "og:image", content: nil) %>

<% for tag_name in post.tags.map(&:name) do%>
  <%= tag(:meta, property: "article:tag", content: tag_name) %>
<% end %>

<% # TODO: Support published time %> 
<%= tag(:meta, property: "article:published_time", 
  content: post.created_at.to_s(:iso8601)) %>

<%= tag(:meta, property: "article:modified_time", 
  content: post.updated_at.to_s(:iso8601)) %>
  
<!-- Twitter Card tags -->
<%= tag(:meta, property: "twitter:card", content: "summary_large_image") %>
<%= tag(:meta, property: "twitter:site", content: blogit_conf.twitter_username) %>
<%= tag(:meta, property: "twitter:creator", 
  content: post.blogger_twitter_username || blogit_conf.twitter_username) %>
<%= tag(:meta, property: "twitter:title", content: title) %>
<%= tag(:meta, property: "twitter:description", content: description) %>
<% # TODO: Support images in blogit (sorry) %> 
<%= tag(:meta, property: "twitter:time", content: nil) %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post.html.erb
<%= content_tag(:article, id: "blogit_post_#{post.id}", 
  class: "blogit_post blog_post--is_preview") do %>

  <%# Render the header for this blog post %>
  <%= render "blogit/posts/post_head", post: post %>
  
  <%= render "blogit/posts/blogger_information", post: post %>
  
  <%# Render the body of this blog post (as Markdown) %>
  <%= format_content(post.short_body) %>

  <%# Render the no. of comments %>
  <%= render "blogit/posts/comments_count",
    post: post if defined?(show_comments_count) and show_comments_count %>

<% end %>

app/views/blogit/posts/_post_footer.html.erb
<% # Left blank, but it's here to replace if you want a post footer %>

app/views/blogit/posts/_post_head.html.erb
<%= content_tag(:h1, class: "blogit_post__header") do %>
  <%= link_to(post.title, post, class: "blogit_post__header_link") %>
<% end %>

app/views/blogit/posts/_related_post.html.erb
<div class="blogit_related_post">
  <%= link_to related_post.title, post_path(related_post), 
    class: "blogit_related_post__title" %>
</div>

app/views/blogit/posts/_share_bar.html.erb
<div id="blogit_share_bar">

  <div class="blogit_share_bar__social_button blogit_share_bar__social_button--google_plus">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div class="blogit_share_bar__social_button blogit_share_bar__social_button--twitter">    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div class="blogit_share_bar__social_button blogit_share_bar__social_button--facebook"> 
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>

</div>

app/views/blogit/posts/_tags.html.erb
<div id="blogit_tags">
  <h3 class="blogit_tags__header blogit_header--section">
    <%= t :tags, :scope => "blogit.posts" %>
  </h3>
  <ul class="blogit_tags__list">
    <%= render partial: "blogit/tags/tag", collection: post.tag_list %>
  </ul>
</div>

app/views/blogit/posts/index.html.erb
<% if params[:tag] %>
  <h2 class="blogit_header--page">
    <%= t(:showing_posts_tagged_with, scope: "blogit.posts", tag: params[:tag])  %>
  </h2>
<% end %>

<div class="blogit_posts_list">
  <% if @posts.any? %>
    <%= render partial: "blogit/posts/post",
      collection: @posts,
      spacer_template: "blog_post_spacer",
      locals: { 
        show_comments_count: (Blogit.configuration.include_comments == :active_records) 
      }  %>
  <% else %>

    <%= render partial: "blogit/posts/empty" %>

  <% end %>
</div>

<%= render "pagination" %>

app/views/blogit/posts/show.html.erb
<% title @post.title %>
<% description @post.description.to_s %>

<%= content_tag(:article, id: "blogit_post_#{@post.id}", class: "blogit_post") do %>

  
  <%# Render the header for this blog post %>
  <%= render "blogit/posts/post_head", post: @post %>

  <%= render "blogit/posts/blogger_information", post: @post %>

  <%# Render the body of this blog post (as Markdown) %>
  <%= format_content(@post.body) %>

  <%# Render info about the person who wrote this post %>
  <%= share_bar_for_post @post %>

  <%# Render the no. of comments %>
  <%= render "blogit/posts/comments_count",
    post: post if defined?(show_comments_count) and show_comments_count %>

  <%= render "blogit/posts/tags", post: @post %>
  <%= render "blogit/posts/related", post: @post %>

  <%= comments_for_post @post %>

<% end %>